blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Define the URL patterns for Blogs"""

from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Blog posts
    # Make sure the name is the same as the name called in the urls, it matches the name not the function name!
    path('blogs/', views.blog, name='blog'),
    # Edit the blog post
    # Here it will take the variable and send the ID to the function to process correct post
    path('blogs/edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    # Adding a new blog post
    path('blogs/add_blog/', views.add_blog, name='add_blog'),
    # Deleting a post created
    path('blogs/delete_post/<int:blog_id>/', views.delete_post, name='delete_post'),
]

users/urls.py
"""Define the URL patterns for the user"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Including the default authorisation URLs.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    """A blog post the user writes about"""
    
    title = models.CharField(max_length=200) # Title for the post
    text = models.TextField() # The event to write about    
    date_added = models.DateTimeField(auto_now_add=True) # Adding the date 
    # Associate the blogpost with each user (upon deleting all posts with associated user deleted)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the blog post title"""
        if len(self.title) > 50:
            return f"{self.title[:50]} ..."
        else:
            return f"{self.title}"
    

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        lables = {'title': '', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 60})}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib import messages

from .models import BlogPost
from.forms import BlogForm

def check_user_post(request, post):
    """Check if the user wanting to edit the post is associated with it"""
    if post.owner != request.user:
        raise Http404

# CREATE YOUR VIEWS HERE.
def index(request):
    """The home page of the blog site"""
    return render(request, 'blogs/index.html')

@login_required
def blog(request):
    """Page containing the blog posts"""
    blogposted = BlogPost.objects.order_by('-date_added')
    
    context = {'blogposted': blogposted}
    return render(request, 'blogs/home.html', context)

# Want to make sure the user is logged in before edit/add blog post.
@login_required
def edit_blog(request, blog_id): 
    """Edit the blog posted """
    #blogpost = BlogPost.objects.get(id=blog_id)
    blogpost = get_object_or_404(BlogPost, id=blog_id)
    # Check if the user requested to edit owns the post.
    check_user_post(request, blogpost)
    
    if request.method != 'POST':
        form = BlogForm(instance=blogpost)        
    else:
        form = BlogForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog')
        
    # Display a blank format
    # Should pass blog to the template in your view. Since you're editing a specific blog post, you should pass the blogpost variable to the template instead.
    context = {'form': form, 'blogpost': blogpost}
    return render(request, 'blogs/edit_blog.html', context) # Then in your edit_blog.html template, use blogpost.id instead of blog.id

# Want to make it so the user can delete his own posts
@login_required
def delete_post(request, blog_id):
    """Deleting a Post"""
    blogpost = get_object_or_404(BlogPost, id=blog_id)
    # Need to check if the request by the user is of his own post.
    check_user_post(request, blogpost)
    
    context = {'post': blogpost}
    # View a page to make sure the user wants to delete the post
    if request.method == 'GET':
        return render(request, 'blogs/post_confirm_delete.html', context)
    
    elif request.method =='POST':
        # Delete the POST
        blogpost.delete()
        # Create a flash message and redirect the user to the blog posts page.
        #messages.success(request, 'The post has been deleted successfully!')
        return redirect('blogs:blog')

# Want to make sure the user is logged in before edit/add blog post.       
@login_required
def add_blog(request):
    """Adding a new blog post"""
    # Do not need Blog ID because adding a new one that does not exist yet
    if request.method != 'POST':
        # Creating a blank form
        form = BlogForm()
    else: 
        form = BlogForm(data=request.POST)
        if form.is_valid():
            # Need to associate the user with the new post
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            
            return redirect('blogs:blog')
    
    # Returning a blank form if not valid or error
    context = {'form': form}
    return render(request, 'blogs/add_blog.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Registering a new user."""
    if request.method != 'POST':
        # Display a blank registration form
        form = UserCreationForm()
    else: 
        # Process completed form
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            # Want to save the new user into the database
            new_user = form.save()
            # Want to directly login the new user
            login(request, new_user)
            # Send back to the home page
            return redirect('blogs:blog')
    
    # Returning a blank form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/add_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Adding a new Post</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'blogs:add_blog' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Post</button>
        {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>OwnBlog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            OwnBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:blog' %}">
                        Posts</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:add_blog' %}">
                        Add Post</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{user.username}}.</span>
                </li>
                <li class="nav-item">
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link">Log out</button>
                    </form>  
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="mb-2 pb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit Blog</h2>
{% endblock page_header %}

{% block content %}

<!--Pass in the id from the blogpost variable saved in the context dictionary that will be parsed in the view function-->
<form action="{% url "blogs:edit_blog" blogpost.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/home.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h3>Blogs Posted</h3>
{% endblock page_header %}

{% block content %}

{% for blog in blogposted %}
    <style>
        .date-right {
            float: right;
        }
    </style>

    <div class="card mb-5">
        <h4 class="card-header">
            <span>{{ blog.owner }} | {{blog.title}}</span> 
            <span class="date-right">{{ blog.date_added|date:'M d - Y' }}</span>
        </h4>
        <div class="card-body">
            {{blog.text}}
        </div>
        <div class="card-footer">
            <a href="{% url "blogs:edit_blog"  blog.id %}" class="card-link">Edit</a>
            <a href="{% url "blogs:delete_post"  blog.id %}" class="card-link">Delete</a>   
        </div>
    </div>
{% empty %}
    <p>Nothing posted yet!</p>
{% endfor %}

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}

    <div class="jumbotron">
        <h1 class="display-4">Follow your adventure!</h1>
        <p class="lead">Create your OwnBlog, and follow the journey of yourself and others. 
            Whenever you have doen something in your life share it with other persons, 
            create a post t let them know what you have been up to.
        </p>
        <hr class="my-4">
        <p>Register to start creating posts of what you've been up to.<p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>    
    </div>
{% endblock page_header %}

blogs/templates/blogs/post_confirm_delete.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}

    <h2>Delete Post</2>

{% endblock page_header %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure that you want to delete the post "{{post.title}}"?</p>
        <div>
            {% buttons %}
                <button type="submit" class="btn btn-primary">Yes, Delete</button>
            {% endbuttons %}
            <a href="{% url "blogs:blog" %}">Cancel</a>
        </div>
    </form>
{% endblock content %}